/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import system.user.Manager;
import system.user.Person;

/**
 *
 * 
 */
public class JfrmManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form JfrmManagerDashboard
     */
    private static Manager mgr;
    
    public JfrmManagerDashboard(Person psn) throws SQLException, ClassNotFoundException {
        initComponents();
        mgr=new Manager(psn.getUNm());
        mgr.setWhNo();
        lblUNm.setText(psn.getUNm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        lblUNm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItmGRNDetails = new javax.swing.JMenuItem();
        mItmMatDetails = new javax.swing.JMenuItem();
        mItmStkDetails = new javax.swing.JMenuItem();
        mItmSplDetails = new javax.swing.JMenuItem();
        mItmSplMatDetails = new javax.swing.JMenuItem();
        mItmWhDetails = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mItmchangePw = new javax.swing.JMenuItem();
        mItmChngProfile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItmUpdtStkDtl = new javax.swing.JMenuItem();
        mItmUpdtStkInv = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");

        lblUNm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUNm.setForeground(new java.awt.Color(0, 0, 204));
        lblUNm.setText("User ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Manager");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Logged In");

        btnLogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jMenu1.setText("View");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmGRNDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mItmGRNDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmGRNDetails.setText("GRN Details");
        mItmGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmGRNDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmGRNDetails);

        mItmMatDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mItmMatDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmMatDetails.setText("Material Details");
        mItmMatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmMatDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmMatDetails);

        mItmStkDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mItmStkDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmStkDetails.setText("Stock Details");
        mItmStkDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmStkDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmStkDetails);

        mItmSplDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mItmSplDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmSplDetails.setText("Supplier Details");
        mItmSplDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmSplDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmSplDetails);

        mItmSplMatDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mItmSplMatDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmSplMatDetails.setText("Supplier/Material Details");
        mItmSplMatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmSplMatDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmSplMatDetails);

        mItmWhDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mItmWhDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmWhDetails.setText("Warehouse Details");
        mItmWhDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmWhDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmWhDetails);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Profile");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmchangePw.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mItmchangePw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmchangePw.setText("change password");
        mItmchangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmchangePwActionPerformed(evt);
            }
        });
        jMenu5.add(mItmchangePw);

        mItmChngProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mItmChngProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmChngProfile.setText("view/update  profile");
        mItmChngProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmChngProfileActionPerformed(evt);
            }
        });
        jMenu5.add(mItmChngProfile);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Update");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmUpdtStkDtl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mItmUpdtStkDtl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmUpdtStkDtl.setText("Stock Details");
        mItmUpdtStkDtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmUpdtStkDtlActionPerformed(evt);
            }
        });
        jMenu2.add(mItmUpdtStkDtl);

        mItmUpdtStkInv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mItmUpdtStkInv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmUpdtStkInv.setText("Stock Inventory");
        mItmUpdtStkInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmUpdtStkInvActionPerformed(evt);
            }
        });
        jMenu2.add(mItmUpdtStkInv);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 148, Short.MAX_VALUE)
                .addComponent(lblUNm, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUNm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItmUpdtStkDtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmUpdtStkDtlActionPerformed
        new JfrmUpdateStockDetails(this.mgr).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmUpdtStkDtlActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new JfrmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void mItmUpdtStkInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmUpdtStkInvActionPerformed
        
        try{
            new JfrmUpdateStockInventory(mgr).setVisible(true);
            dispose();
        } catch (SQLException | ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_mItmUpdtStkInvActionPerformed

    private void mItmchangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmchangePwActionPerformed
        new JfrmChangePassword(this.mgr).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmchangePwActionPerformed

    private void mItmChngProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmChngProfileActionPerformed
        
        try{
            new JfrmUserProfile(mgr).setVisible(true);
            dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mItmChngProfileActionPerformed

    private void mItmSplDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmSplDetailsActionPerformed
            new JfrmViewSupplier(mgr).setVisible(true);
            dispose();
    }//GEN-LAST:event_mItmSplDetailsActionPerformed

    private void mItmMatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmMatDetailsActionPerformed
        new JfrmViewMaterial(mgr).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmMatDetailsActionPerformed

    private void mItmSplMatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmSplMatDetailsActionPerformed
        try{
            new JfrmViewSupplierMaterial(mgr).setVisible(true);
            dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mItmSplMatDetailsActionPerformed

    private void mItmWhDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmWhDetailsActionPerformed
        new JfrmViewManagerWarehouseDetails(mgr).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmWhDetailsActionPerformed

    private void mItmStkDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmStkDetailsActionPerformed
        new JfrmViewManagerStockDetails(mgr).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmStkDetailsActionPerformed

    private void mItmGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmGRNDetailsActionPerformed
       new JfrmViewManagerGRNDetails(mgr).setVisible(true);
       dispose();
    }//GEN-LAST:event_mItmGRNDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblUNm;
    private javax.swing.JMenuItem mItmChngProfile;
    private javax.swing.JMenuItem mItmGRNDetails;
    private javax.swing.JMenuItem mItmMatDetails;
    private javax.swing.JMenuItem mItmSplDetails;
    private javax.swing.JMenuItem mItmSplMatDetails;
    private javax.swing.JMenuItem mItmStkDetails;
    private javax.swing.JMenuItem mItmUpdtStkDtl;
    private javax.swing.JMenuItem mItmUpdtStkInv;
    private javax.swing.JMenuItem mItmWhDetails;
    private javax.swing.JMenuItem mItmchangePw;
    // End of variables declaration//GEN-END:variables
}
