/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import system.user.Manager;
import system.user.Person;
import system.user.Supervisor;

/**
 *
 * 
 */
public class JfrmSupervisorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form JfrmSupervisorDashboard
     */
    private static Supervisor sup;
    
    public JfrmSupervisorDashboard(Person psn) throws SQLException, ClassNotFoundException{
        initComponents();
        sup=new Supervisor(psn.getUNm());
        sup.setWhNo();
        lblUNm.setText(psn.getUNm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUNm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItmGRNDetails = new javax.swing.JMenuItem();
        MItmMatDetails = new javax.swing.JMenuItem();
        mItmStkDetails = new javax.swing.JMenuItem();
        mItmSplDetails = new javax.swing.JMenuItem();
        mItmSupMatDetails = new javax.swing.JMenuItem();
        mItmWhDetails = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mItmChngPw = new javax.swing.JMenuItem();
        mItmChngProfile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItmGRN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supervisor Dashboard");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Logged In");

        lblUNm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUNm.setForeground(new java.awt.Color(0, 0, 204));
        lblUNm.setText("User ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Supervisor");

        btnLogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("View");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmGRNDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mItmGRNDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmGRNDetails.setText("GRN Details");
        mItmGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmGRNDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmGRNDetails);

        MItmMatDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MItmMatDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MItmMatDetails.setText("Material Details");
        MItmMatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItmMatDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(MItmMatDetails);

        mItmStkDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mItmStkDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmStkDetails.setText("Stock Details");
        mItmStkDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmStkDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmStkDetails);

        mItmSplDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mItmSplDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmSplDetails.setText("Supplier Details");
        mItmSplDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmSplDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmSplDetails);

        mItmSupMatDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mItmSupMatDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmSupMatDetails.setText("Supplier/Material Details");
        mItmSupMatDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmSupMatDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmSupMatDetails);

        mItmWhDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mItmWhDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmWhDetails.setText("Warehouse Details");
        mItmWhDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmWhDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(mItmWhDetails);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Profile");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmChngPw.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mItmChngPw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmChngPw.setText("change password");
        mItmChngPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmChngPwActionPerformed(evt);
            }
        });
        jMenu5.add(mItmChngPw);

        mItmChngProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mItmChngProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmChngProfile.setText("view/update  profile");
        mItmChngProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmChngProfileActionPerformed(evt);
            }
        });
        jMenu5.add(mItmChngProfile);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Update");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItmGRN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mItmGRN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mItmGRN.setText("GRN");
        mItmGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmGRNActionPerformed(evt);
            }
        });
        jMenu2.add(mItmGRN);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addComponent(lblUNm, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUNm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItmGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmGRNActionPerformed
        try{
            new JfrmUpdateGRN(this.sup).setVisible(true);
            dispose();
        } 
        catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_mItmGRNActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new JfrmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void mItmChngPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmChngPwActionPerformed
        new JfrmChangePassword(sup).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmChngPwActionPerformed

    private void mItmChngProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmChngProfileActionPerformed
        try{
            new JfrmUserProfile(sup).setVisible(true);
            dispose();
        } 
        catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mItmChngProfileActionPerformed

    private void mItmSplDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmSplDetailsActionPerformed
        new JfrmViewSupplier(sup).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmSplDetailsActionPerformed

    private void MItmMatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItmMatDetailsActionPerformed
        new JfrmViewMaterial(sup).setVisible(true);
        dispose();
    }//GEN-LAST:event_MItmMatDetailsActionPerformed

    private void mItmSupMatDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmSupMatDetailsActionPerformed
        try{
            new JfrmViewSupplierMaterial(sup).setVisible(true);
            dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mItmSupMatDetailsActionPerformed

    private void mItmWhDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmWhDetailsActionPerformed
        try{
            new JfrmViewSupervisorWarehouseDetails(sup).setVisible(true);
            dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mItmWhDetailsActionPerformed

    private void mItmStkDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmStkDetailsActionPerformed
        new JfrmViewSupervisorStockDetails(sup).setVisible(true);
            dispose();
    }//GEN-LAST:event_mItmStkDetailsActionPerformed

    private void mItmGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmGRNDetailsActionPerformed
        new JfrmViewSupervisorGRNDetails(sup).setVisible(true);
        dispose();
    }//GEN-LAST:event_mItmGRNDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmSupervisorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmSupervisorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmSupervisorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmSupervisorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        
            /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MItmMatDetails;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUNm;
    private javax.swing.JMenuItem mItmChngProfile;
    private javax.swing.JMenuItem mItmChngPw;
    private javax.swing.JMenuItem mItmGRN;
    private javax.swing.JMenuItem mItmGRNDetails;
    private javax.swing.JMenuItem mItmSplDetails;
    private javax.swing.JMenuItem mItmStkDetails;
    private javax.swing.JMenuItem mItmSupMatDetails;
    private javax.swing.JMenuItem mItmWhDetails;
    // End of variables declaration//GEN-END:variables
}
