/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.gui;

import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import system.user.Person;

/**
 *
 * 
 */
public class JfrmChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form JfrmChangePassword
     */
    private static Person psn;
    
    public JfrmChangePassword(Person psn) {
        initComponents();
        this.psn=psn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDash = new javax.swing.JButton();
        btnChng = new javax.swing.JButton();
        txtCurPw = new javax.swing.JPasswordField();
        txtNewPw = new javax.swing.JPasswordField();
        txtCNewPw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Current Password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("New Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Confirm New Password");

        btnDash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDash.setText("<<Dashboard");
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        btnChng.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChng.setText("Change");
        btnChng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChngActionPerformed(evt);
            }
        });

        txtCurPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNewPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCNewPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChng)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnDash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCurPw, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtNewPw)
                            .addComponent(txtCNewPw))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnDash)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChng)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        
        try{
            char pr=psn.getPrv();
        
            switch(pr)
            {
                case 'M':
                    new JfrmManagerDashboard(psn).setVisible(true);
                    dispose();
                    break;
                case 'S':
                    new JfrmSupervisorDashboard(psn).setVisible(true);
                    dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Privilage Issue, Please contact System administrator :", "Privilage Issue", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (ClassNotFoundException | SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnChngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChngActionPerformed
        String psw, nwPsw, cnfmPsw;
        boolean lg=false, cnfm=false;
        
        psw=txtCurPw.getText();
        nwPsw=txtNewPw.getText();
        cnfmPsw=txtCNewPw.getText();
        
        this.psn.setPw(psw);
        try{
            
            lg=this.psn.login();
            
            if(lg==true)
            {
                if(nwPsw.equals(cnfmPsw))
                {
                    cnfm=psn.chngPw(nwPsw);
                    if(cnfm==true)
                    {
                        int i=JOptionPane.showConfirmDialog(null, "Do you need to change your password?", "Are you sure", JOptionPane.INFORMATION_MESSAGE);
                        if(i==JOptionPane.YES_OPTION)
                        {
                            JOptionPane.showMessageDialog(null, "Your Password is changed Successfully!"
                            , "Password Changed", JOptionPane.INFORMATION_MESSAGE);
                            txtCurPw.setText(null);
                            txtNewPw.setText(null);
                            txtCNewPw.setText(null);
                        }
                        else
                        {
                            txtCurPw.setText(null);
                            txtNewPw.setText(null);
                            txtCNewPw.setText(null);
                        }
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(null, "Oops something went wrong while changing your password!"
                        , "Password Change Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "The values entered for the new password & confirm password fields doesn't "
                        + "match with each other. Please re-enter matching values to them." , "Password Mismatch", JOptionPane.ERROR_MESSAGE);
                    txtCurPw.setText(null);
                    txtNewPw.setText(null);
                    txtCNewPw.setText(null);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The current Password you entered is invalid, Please re-enter "
                        + "your current password" , "Invalid Password", JOptionPane.ERROR_MESSAGE);
                txtCurPw.setText(null);
                txtNewPw.setText(null);
                txtCNewPw.setText(null);
            }
        }
        catch(SQLException | NoSuchAlgorithmException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChng;
    private javax.swing.JButton btnDash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtCNewPw;
    private javax.swing.JPasswordField txtCurPw;
    private javax.swing.JPasswordField txtNewPw;
    // End of variables declaration//GEN-END:variables
}
