/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import system.user.Manager;
import system.user.Material;
import system.user.Stock;
import system.user.Warehouse;

/**
 *
 * 
 */
public class JfrmUpdateStockInventory extends javax.swing.JFrame {

    /**
     * Creates new form JfrmUpdtStockInventory
     */
    private static Manager mgr;
    
    public JfrmUpdateStockInventory(Manager mgr) throws SQLException, ClassNotFoundException{
        initComponents();
        this.mgr=mgr;
        txtQty.setText("0");
        txtQty.enable(false);
        
        mgr.getWhNo().forEach((s) -> {
            cmbWhNo.addItem(s);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtOrdLvl = new javax.swing.JTextField();
        txtMaxQty = new javax.swing.JTextField();
        btnAdStk = new javax.swing.JButton();
        btnDash = new javax.swing.JButton();
        cmbWhNo = new javax.swing.JComboBox<>();
        cmbMatNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Stock Inventory");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Warehouse No");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Material No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Available Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Order Level");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Maximum Qantity");

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtOrdLvl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMaxQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAdStk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdStk.setText("Add Stock");
        btnAdStk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdStkActionPerformed(evt);
            }
        });

        btnDash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDash.setText("<<Dashboard");
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        cmbWhNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbWhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWhNoActionPerformed(evt);
            }
        });

        cmbMatNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbMatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDash)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaxQty)
                            .addComponent(txtOrdLvl)
                            .addComponent(cmbMatNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQty)
                            .addComponent(cmbWhNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 85, Short.MAX_VALUE)
                                .addComponent(btnAdStk)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnDash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbWhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMatNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOrdLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaxQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdStk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        try {
            new JfrmManagerDashboard(mgr).setVisible(true);
            dispose();
        } 
        catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDashActionPerformed

    private void cmbWhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWhNoActionPerformed
        
        String whNo=(String)cmbWhNo.getSelectedItem();
        List<String> allMatOrg=new ArrayList<>();
        List<String> allMatChg=new ArrayList<>();
        
        cmbMatNo.removeAllItems();
        
        boolean avl=false;
        int indx=0;
        
        try{
            allMatOrg=Material.listMaterial();
            //JOptionPane.showMessageDialog(null, "Step1" );
            
            for(String s: allMatOrg)
            {
               avl=Stock.isAvailable(whNo,s);
               //JOptionPane.showMessageDialog(null, "Step2" );
               if(avl==false)
               {
                   allMatChg.add((String)allMatOrg.get(indx));
                   //JOptionPane.showMessageDialog(null, "Step3" );
               }
               
               avl=false;
               indx++;
            }
        }
        catch(SQLException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
        }
        
        allMatChg.forEach((s)->{
            cmbMatNo.addItem(s);
        });
    }//GEN-LAST:event_cmbWhNoActionPerformed

    private void cmbMatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatNoActionPerformed
        
    }//GEN-LAST:event_cmbMatNoActionPerformed

    private void btnAdStkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdStkActionPerformed
        String whNo=(String)cmbWhNo.getSelectedItem();
        String matNo=(String)cmbMatNo.getSelectedItem();
        double qty=0, ordLvl=0, maxQty=0, exStk=0;
        String oLvl=txtOrdLvl.getText();
        String mQty=txtMaxQty.getText();
        Stock stk=null;
        Warehouse wh=new Warehouse(whNo);
        ResultSet rs=null;
        boolean updt=false;
        int cnfm;
        
        if(oLvl.isEmpty() | mQty.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Feilds Order Level & Max Quantity can't be left blank when updating" , "Validation Issue", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
              try{
                  ordLvl=Double.parseDouble(oLvl);
                  maxQty=Double.parseDouble(mQty);
              }
              catch(NumberFormatException ex)
              {
                  JOptionPane.showMessageDialog(null, "Please enter Numeric values for Order Level & Maximum Quantity and retry :", "Validation Issue", JOptionPane.WARNING_MESSAGE);
                  return;
              }
        }
             
        if(ordLvl<1000 | maxQty<1000)
        {
            JOptionPane.showMessageDialog(null, "Order Level & Maximum Quantity can't be lesser than 1000" , "Validation Issue", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            stk=new Stock(whNo, matNo);
            try{
                
                wh.pullWhDtls();
                exStk=stk.pullExStock();
                
                if(wh.getStrgSpc()>(maxQty+exStk))
                {
                    cnfm=JOptionPane.showConfirmDialog(null,"Are you sure you want to Add this Stock", "Confirm Stock Add", JOptionPane.INFORMATION_MESSAGE);

                    if(cnfm==JOptionPane.YES_OPTION)
                    {
                        stk=new Stock(whNo, matNo, qty, ordLvl, maxQty);

                        updt=stk.insertStock();
                        

                        if(updt==true)
                        {
                            JOptionPane.showMessageDialog(null, "Stock Inventory Updated Successfully!", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
                            cmbWhNo.setSelectedIndex(0);
                            txtMaxQty.setText(null);
                            txtOrdLvl.setText(null);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Stock Inventory Update Failed!", "Update Failed", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null, "The Maximum Storage space requested can't be allocated in the warehouse "
                            + "\nWareHouse Capacity: " + wh.getStrgSpc() + "\nCapacity already utilized: " + exStk 
                            + "\nCapasity Required to Allocate Stock: " + (maxQty+exStk), 
                            "Storage space Issue", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException | ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Oops Something went Wrong :" + ex.getMessage(), "Runtime Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnAdStkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmUpdateStockInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmUpdateStockInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmUpdateStockInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmUpdateStockInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdStk;
    private javax.swing.JButton btnDash;
    private javax.swing.JComboBox<String> cmbMatNo;
    private javax.swing.JComboBox<String> cmbWhNo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMaxQty;
    private javax.swing.JTextField txtOrdLvl;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
